### ISSUE TITLE
Test on GPUArrays

### ISSUE THREAD

**Issue by dfdx** [dfdx/XDiff.jl#14]

**Comment by dfdx** [comment]
A couple of bugs preventing XDiff to work smoothly on GPUArrays: 

 - JuliaGPU/GPUArrays.jl#53
 - JuliaGPU/GPUArrays.jl#54

Most of the code works fine though, giving 4-5X speedup on my GeForce GTX 960M.

**Comment by dfdx** [comment]
It turns out to be quite hard to generate generic code for all kinds of GPUArrays at the moment, so I've restricted my effort to CUDA backend for now. Currently there's `CuCodeGen` that works with GPUArrays initialized with `:cudanative` backend and outputs code for `Float64` arrays due to JuliaGPU/GPUArrays.jl#65. Using `Float64` is suboptimal, so results are controversial - on some tests and problem sizes it gives 2-3 performance boost, on others - 1.5-2 slowdown.

**Comment by jekbradbury** [comment]
I think the CUDA backend of GPUArrays is [about to be deprecated](https://github.com/JuliaGPU/GPUArrays.jl/pull/64) in favor of [CuArrays](https://github.com/FluxML/CuArrays.jl) while GPUArrays becomes a package of abstract type specifications implemented by CuArrays and CLArrays?

**Comment by dfdx** [comment]
Sounds good! I'll check if pure CuArray works with `Float32` and post back here.

**Comment by dfdx** [comment]
I've tested CuArrays in XGrad.jl extensively and everything seems to work fine.
